version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test-python-install:
          version: "3.8"
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            pip install -r dependencies/requirement-dev.txt
      - run:
          name: run tests
          command: |
            pytest --cov --cov-report=html
      - store_artifacts:
          path: htmlcov/
  test-python-install:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
           pip install -r dependencies/requirement-dev.txt
      - run:
          name: run tests
          command: |
            pytest --cov --cov-report=html
      - store_artifacts:
          path: htmlcov/
      - run:
          name: Smoke Test Install
          command: |
            pip install -e .
            python --version
            pip install kitten-box
            python -c "from kitten_box import *"
  deploy:
    docker:
      - image:  cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
           pip install -r dependencies/requirement-dev.txt
      - run:
          name: verify git tag vs. version
          command: |
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = nussopasit" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            pip install twine
            twine upload dist/*
#V0.1